version: '3.7'

services:
  app:
    container_name: gg_backend
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    entrypoint: /bin/bash docker/deploy/entrypoint.sh
    restart: unless-stopped
    depends_on:
       mysql:
          condition: service_healthy
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 2345:2345

  mysql:
    container_name: gg_mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

